spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
          auto-create-topics: true
          configuration:
            auto.offset.reset: latest
      bindings:
        greetings-in:
          destination: greetings-sample
          group: greetings-in-group
          contentType: application/json
        greetings-out:
          destination: dev-booking-cona23
          contentType: application/json
          producer:
            headerMode: headers
server:
  port: 8087            
            
